(define (loop? x)
  (define (move p1 p2)
    (cond ((null? p1) #f)
          ((eq? p1 p2) #t)
          ((null? (cdr p1)) #f)
          ((eq? (cdr p1) p2) #t)
          (else (move (cdr (cdr p1)) (cdr p2)))))
  (if (null? x)
      (#f)
      (move (cdr x) x)))
